/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    crossIcon: "#212B46",
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    borderColor: "#D9D9D9",
    borderColorSelected: "#2DB9B0",
    backgroundSelected: "#DCFFFB",
    radioBorderColorSelected: "#1EA6D6",
    textSelected: "#32383D",
    cardBackgroud: '#F6F5FA',
    slotBorderSelected: "#1EA6D6",
    slotBackgroundSelected: "#1EA6D6",
    dotColor: "#A9A9AB",
    pendingBg: "#FFEECB",
    pendingText: "#FF7D53",
    acceptedBg: "#1EA6D666",
    acceptedText: "#1EA6D6",
    completedBg: "#DEFFE9",
    completedText: "#197E3E",
    cancelledBg: "#FFD2E5",
    cancelledText: "#EE2279",
    errorBorder: "#EB3639",
    errorBackground: "#FFE5E5",
    successBorder: "#059286",
    successBackground: "#99E4DF",
    subText: "#757575",
    bannerInfoBg: "#FFB73F",
    bannerInfoText: "#32383D",
    bannerInfoSubText: "#fff",
    appointmentIcon: "#1EA6D6",
    slotLockedBg: "#FFCB2D",
    slotLockedText: "#74512D",
    slotBookedBg: "#99E4DF",
    slotBookedText: "#23918A"
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#fff',
    tabIconDefault: '#fff',
    tabIconSelected: tintColorDark,
    borderColor: "#D9D9D9",
    borderColorSelected: "#2DB9B0",
    backgroundSelected: "#DCFFFB",
    radioBorderColorSelected: "#1EA6D6",
    textSelected: "#32383D",
    cardBackgroud: '#303135',
    slotBorderSelected: "#1EA6D6",
    slotBackgroundSelected: "#1EA6D6",
    dotColor: "#A9A9AB",
    pendingBg: "#FFEECB",
    pendingText: "#FF7D53",
    acceptedBg: "#1EA6D666",
    acceptedText: "#1EA6D6",
    completedBg: "#DEFFE9",
    completedText: "#197E3E",
    cancelledBg: "#FFD2E5",
    cancelledText: "#EE2279",
    errorBorder: "#EB3639",
    errorBackground: "#FFE5E5",
    successBorder: "#059286",
    successBackground: "#99E4DF",
    subText: "#757575",
    crossIcon: "#212B46",
    bannerInfoBg: "#FFB73F",
    bannerInfoText: "#fff",
    bannerInfoSubText: "#32383D",
    appointmentIcon: "#1EA6D6",
    slotLockedBg: "#FFCB2D",
    slotLockedText: "#74512D",
    slotBookedBg: "#99E4DF",
    slotBookedText: "#23918A"
  },
};
