export const URLS = {
    BASE: "http://docter-api-service-lb-413222422.ap-south-1.elb.amazonaws.com",
    CREATE_DOCTOR: "/v1/signup/doctor",
    UPDATE_DOCTOR: "/v1/doctor",
    GET_CLINICS: "/v1/clinic",
    UPDATE_CLINIC: "/v1/clinic/update",
    GET_APPOINTMENTS: "/v1/appointment",
    UPDATE_APPOINTMENTS: "/v1/appointment/update",
    LOCAL_BASE: "http://localhost:3000",
    GET_TRANSLATIONS: "/v1/translations",
    GET_PATIENT: "/v1/patient",
    GET_PATIENT_LIST: "/v1/patient/search",
    GET_CONFIG: "/v1/config",
    LOGIN: "/v1/user/login",
    LOGOUT: "/v1/user/logout",
    DFO: "/v1/dfo",
}