export const signUpHeaderDataInitial = [
    {
        label: "Personal Info",
        status: "STARTED",
    },
    {
        label: "Clinic Info",
        status: "NOT_STARTED",
    },
    {
        label: "ID Proof",
        status: "NOT_STARTED",
    }
];

export const signUpDetailsInitial = {
    phoneOTPDetails: {
      phoneNumber: "",
      otpTriggered: false,
      otp: "",
    },
    imageUrl: "",
    personalDetails: [
      {
          id: "fullName",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Full Name",
          isMandatory: true,
          errorMessage: "Please provide your full name.",
          placeholder: "Enter your full name",
      },
      {
          id: "gender",
          type: "STRING",
          inputType: "RADIO",
          value: "",
          label: "Gender",
          isMandatory: true,
          errorMessage: "Please select your gender",
          options: ["MALE", "FEMALE", "OTHER"],
      },
      {
        id: "email",
        type: "STRING",
        inputType: "EMAIL",
        value: "",
        label: "Email",
        isMandatory: false,
        errorMessage: "Please enter a valid email Id",
      },
      {
          id: "experience",
          type: "STRING",
          inputType: "NUMBER",
          value: "",
          label: "Experience (in years)",
          isMandatory: true,
          errorMessage: "Please provide your experience",
          placeholder: "Enter your experience in years",
      },
      {
          id: "specialisation",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Specialisation",
          isMandatory: true,
          errorMessage: "Please enter a valid specialisation",
          placeholder: "Enter specialisation",
      },
      {
          id: "otherQualification",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Other Qualification",
          isMandatory: false,
          errorMessage: "",
          placeholder: "Enter your qualifications",
      },
      {
        id: "languages",
        type: "STRING",
        inputType: "BOXES",
        value: [],
        label: "Languages",
        isMandatory: true,
        errorMessage: "Please select atleast 1 language",
        placeholder: "Select maximum 3 languages",
      }
    ],
    clinicDetails: [
      {
          id: "clinicName",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Clinic Name",
          isMandatory: true,
          errorMessage: "Please enter your clinic name",
          placeholder: "Clinic Name",
      },
      {
          id: "clinicAddress",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Clinic Address",
          isMandatory: true,
          errorMessage: "Please enter your clinic address",
          placeholder: "12, Street Name",
      },
      {
          id: "landmark",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Landmark",
          isMandatory: false,
          errorMessage: "",
          placeholder: "Near Ganesh Temple",
      },
      {
          id: "city",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "City",
          isMandatory: true,
          errorMessage: "Please enter your city",
          placeholder: "Ambala",
      },
      {
        id: "state",
        type: "STRING",
        inputType: "TEXT",
        value: "",
        label: "State",
        isMandatory: true,
        errorMessage: "Please enter your state",
        placeholder: "Haryana",
    },
      {
          id: "pincode",
          type: "STRING",
          inputType: "NUMBER",
          value: "",
          label: "Pincode",
          isMandatory: true,
          errorMessage: "Please enter your pincode",
          placeholder: "133001",
      },
    ],
    idProofDetails: [
      {
          id: "registration",
          label: "Registration Certificate",
          documentType: "REGISTRATION",
          isUploaded: false,
          value: "",
          frontUrl: "",
          backUrl: "",
          docIcon: require('../assets/images/registration.png'),
      },
      {
          id: "aadharCard",
          label: "Aadhar Card",
          documentType: "AADHAR",
          isUploaded: false,
          value: "",
          frontUrl: "",
          backUrl: "",
          docIcon: require('../assets/images/address.png'),
      },
      {
          id: "panCard",
          label: "Pan Card",
          documentType: "PAN",
          isUploaded: false,
          value: "",
          frontUrl: "",
          backUrl: "",
          docIcon: require('../assets/images/address.png'),
      }
    ]
  }