export const signUpHeaderDataInitial = [
    {
        label: "Personal Info",
        status: "STARTED",
    },
    {
        label: "Clinic Info",
        status: "NOT_STARTED",
    },
    {
        label: "ID Proof",
        status: "NOT_STARTED",
    }
];

export const signUpDetailsInitial = {
    phoneOTPDetails: {
      phoneNumber: "",
      otpTriggered: false,
      otp: "",
    },
    imageUrl: "",
    loginDetails: [
        {
            id: "number",
            type: "STRING",
            inputType: "NUMBER",
            value: "",
            label: "Mobile Number",
            isMandatory: true,
            errorMessage: "Please provide your valid phone nmber.",
            placeholder: "9797979797",
        },
        {
            id: "password",
            type: "STRING",
            inputType: "PASSWORD",
            value: "",
            label: "Password",
            isMandatory: true,
            errorMessage: "Please enter minimum 8 digit password.",
            placeholder: "********",
        },
        {
            id: "confirmPassword",
            type: "STRING",
            inputType: "PASSWORD",
            value: "",
            label: "Confirm Password",
            isMandatory: true,
            errorMessage: "Password does not match.",
            placeholder: "********",
        },
    ],
    personalDetails: [
        {
            id: "fullName",
            type: "STRING",
            inputType: "TEXT",
            value: "",
            label: "Full Name",
            initials: "Dr.",
            isMandatory: true,
            errorMessage: "Please provide your full name.",
            placeholder: "Enter your full name",
        },
        {
            id: "gender",
            type: "STRING",
            inputType: "RADIO",
            value: "",
            label: "Gender",
            isMandatory: true,
            errorMessage: "Please select your gender",
            options: ["MALE", "FEMALE", "OTHER"],
        },
        {
            id: "email",
            type: "STRING",
            inputType: "EMAIL",
            value: "",
            label: "Email",
            isMandatory: false,
            errorMessage: "Please enter a valid email Id",
        },
        {
            id: "dob",
            type: "STRING",
            inputType: "DATE",
            value: "",
            label: "Date Of Birth",
            isMandatory: true,
            errorMessage: "Please provide your date of birth",
            placeholder: "21-12-1999"
        },
        {
            id: "experience",
            type: "STRING",
            inputType: "NUMBER",
            value: "",
            label: "Experience (in years)",
            isMandatory: true,
            errorMessage: "Please provide your experience",
            placeholder: "Enter your experience in years",
        },
        {
            id: "graduation",
            type: "STRING",
            inputType: "TEXT",
            value: "",
            label: "Graduation Course",
            isMandatory: true,
            errorMessage: "Please enter a valid graduation",
            placeholder: "Enter graduation course",
        },
        {
            id: "graduationCollege",
            type: "STRING",
            inputType: "TEXT",
            value: "",
            label: "Graduation College",
            isMandatory: true,
            errorMessage: "Please enter a valid college for graduation",
            placeholder: "Enter college for graduation",
        },
        {
            id: "graduationYear",
            type: "STRING",
            inputType: "NUMBER",
            value: "",
            label: "Graduation Passing Year",
            isMandatory: true,
            errorMessage: "Please enter a valid passing year for graduation",
            placeholder: "Enter passing year for graduation",
        },
        {
            id: "specialisation",
            type: "STRING",
            inputType: "SEARCHSELECT",
            value: "",
            label: "Specialisation",
            isMandatory: true,
            errorMessage: "Please enter a valid specialisation",
            placeholder: "Type for specialisation",
        },
        {
            id: "specialisationCollege",
            type: "STRING",
            inputType: "TEXT",
            value: "",
            label: "Specialisation College",
            isMandatory: false,
            errorMessage: "Please enter a valid college for specialisation",
            placeholder: "Enter college for specialisation",
        },
        {
            id: "specialisationYear",
            type: "STRING",
            inputType: "NUMBER",
            value: "",
            label: "Specialisation Passing Year",
            isMandatory: false,
            errorMessage: "Please enter a valid passing year for specialisation",
            placeholder: "Enter passing year for specialisation",
        },
        {
            id: "otherQualification",
            type: "STRING",
            inputType: "TEXT",
            value: "",
            label: "Other Qualification",
            isMandatory: false,
            errorMessage: "",
            placeholder: "Enter your qualifications",
        },
        {
            id: "languages",
            type: "STRING",
            inputType: "BOXES",
            value: [],
            label: "Languages",
            isMandatory: true,
            errorMessage: "Please select atleast 1 language",
            placeholder: "Select maximum 3 languages",
        }
    ],
    clinicDetails: [
      {
          id: "clinicName",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Clinic Name",
          isMandatory: true,
          errorMessage: "Please enter your clinic name",
          placeholder: "Clinic Name",
      },
      {
          id: "clinicAddress",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Clinic Address",
          isMandatory: true,
          errorMessage: "Please enter your clinic address",
          placeholder: "12, Street Name",
      },
      {
          id: "landmark",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "Landmark",
          isMandatory: false,
          errorMessage: "",
          placeholder: "Near Ganesh Temple",
      },
      {
          id: "city",
          type: "STRING",
          inputType: "TEXT",
          value: "",
          label: "City",
          isMandatory: true,
          errorMessage: "Please enter your city",
          placeholder: "Ambala",
      },
      {
        id: "state",
        type: "STRING",
        inputType: "TEXT",
        value: "",
        label: "State",
        isMandatory: true,
        errorMessage: "Please enter your state",
        placeholder: "Haryana",
    },
      {
          id: "pincode",
          type: "STRING",
          inputType: "NUMBER",
          value: "",
          label: "Pincode",
          isMandatory: true,
          errorMessage: "Please enter your pincode",
          placeholder: "133001",
      },
    ],
    idProofDetails: [
      {
          id: "registration",
          label: "Registration Certificate",
          documentType: "REGISTRATION",
          isUploaded: false,
          value: "",
          frontUrl: "",
          backUrl: "",
      },
      {
          id: "aadharCard",
          label: "Aadhar Card",
          documentType: "AADHAR",
          isUploaded: false,
          value: "",
          frontUrl: "",
          backUrl: "",
      },
      {
          id: "panCard",
          label: "Pan Card",
          documentType: "PAN",
          isUploaded: false,
          value: "",
          frontUrl: "",
          backUrl: "",
      }
    ]
  }

export const textObject = {
    id: "number",
    type: "STRING",
    inputType: "Text",
    value: "",
    label: "Remark",
    isMandatory: true,
    errorMessage: "Please provide remark.",
    placeholder: "Message",
    isError: false
};